export type QuestionType =
  | "single"
  | "multi"
  | "text"
  | "longtext"
  | "slider"
  | "rating"
  | "gauge"
  | "rank"
  | "contact";

export type Option = {
  value: string;
  label: string;
  emoji?: string;
  color?: string;
};

export type Question = {
  id: string;
  bloc: number;
  blocTitle: string;
  type: QuestionType;
  question: string;
  hint?: string;
  options?: Option[];
  placeholder?: string;
  optional?: boolean;
  sliderMin?: number;
  sliderMax?: number;
  sliderStep?: number;
  sliderUnit?: string;
  sliderLabels?: { min?: string; max?: string };
  ratingMax?: number;
  rankTopN?: number;
  showIf?: { questionId: string; valueIncludes: string };
};

export const BLOCS = [
  { num: 1, title: "Toi & ton histoire mood", emoji: "🌸" },
  { num: 2, title: "Ta collection actuelle", emoji: "💍" },
  { num: 3, title: "Tes envies nouveautés", emoji: "✨" },
  { num: 4, title: "Les coffrets", emoji: "🎁" },
  { num: 5, title: "La joaillerie", emoji: "💎" },
  { num: 6, title: "Tes habitudes d'achat", emoji: "🛍️" },
  { num: 7, title: "Comment tu nous as connu(e)", emoji: "💫" },
  { num: 8, title: "Notre site, nos photos, notre service", emoji: "📸" },
  { num: 9, title: "L'âme de Mood", emoji: "🌙" },
  { num: 10, title: "Ta pépite rêvée", emoji: "💌" },
];

export const QUESTIONS: Question[] = [
  // ═══════════════════════════════════════════════════════════════
  // BLOC 1 — Toi & ton histoire mood
  // ═══════════════════════════════════════════════════════════════
  {
    id: "tranche_age",
    bloc: 1,
    blocTitle: "Toi & ton histoire mood",
    type: "single",
    question: "Ta tranche d'âge ?",
    hint: "Pour mieux te connaître — ça reste entre nous 🌸",
    options: [
      { value: "moins25", label: "Moins de 25 ans", emoji: "🌱" },
      { value: "25_35", label: "25 à 35 ans", emoji: "🌸" },
      { value: "36_45", label: "36 à 45 ans", emoji: "✨" },
      { value: "46_55", label: "46 à 55 ans", emoji: "💫" },
      { value: "56_65", label: "56 à 65 ans", emoji: "💎" },
      { value: "65plus", label: "Plus de 65 ans", emoji: "👑" },
    ],
  },
  {
    id: "region",
    bloc: 1,
    blocTitle: "Toi & ton histoire mood",
    type: "single",
    question: "Tu vis dans quelle région ?",
    options: [
      { value: "vd", label: "Vaud", emoji: "🏔️" },
      { value: "ge", label: "Genève", emoji: "⛲" },
      { value: "vs", label: "Valais", emoji: "🏔️" },
      { value: "ne", label: "Neuchâtel", emoji: "🌊" },
      { value: "fr", label: "Fribourg", emoji: "🏰" },
      { value: "ju", label: "Jura", emoji: "🌲" },
      { value: "be", label: "Berne", emoji: "🐻" },
      { value: "zh_alemand", label: "Suisse alémanique", emoji: "🇨🇭" },
      { value: "ti", label: "Tessin", emoji: "☀️" },
      { value: "fr_etranger", label: "France ou frontière", emoji: "🇫🇷" },
      { value: "etranger", label: "Autre pays", emoji: "🌍" },
    ],
  },
  {
    id: "anciennete",
    bloc: 1,
    blocTitle: "Toi & ton histoire mood",
    type: "single",
    question: "Depuis quand es-tu une moodeuse ❤️ ?",
    options: [
      { value: "decouvre", label: "Je découvre tout juste", emoji: "🌱" },
      { value: "moins1", label: "Moins d'un an", emoji: "🌸" },
      { value: "1a3", label: "Entre 1 et 3 ans", emoji: "💫" },
      { value: "3a5", label: "Entre 3 et 5 ans", emoji: "✨" },
      { value: "plus5", label: "Plus de 5 ans (fidèle 💎)", emoji: "👑" },
    ],
  },
  {
    id: "nombre_bagues",
    bloc: 1,
    blocTitle: "Toi & ton histoire mood",
    type: "single",
    question: "Combien de bagues mood as-tu (à peu près) ?",
    hint: "Au feeling 😉",
    options: [
      { value: "1a10", label: "1 à 10", emoji: "🤍" },
      { value: "11a30", label: "11 à 30", emoji: "💕" },
      { value: "31a50", label: "31 à 50", emoji: "🩵" },
      { value: "51plus", label: "51 et plus", emoji: "💎" },
      { value: "perdu_compte", label: "J'ai perdu le compte 😄", emoji: "🌹" },
    ],
  },
  {
    id: "frequence",
    bloc: 1,
    blocTitle: "Toi & ton histoire mood",
    type: "single",
    question: "Tu portes mood plutôt...",
    options: [
      { value: "quotidien", label: "Au quotidien, sans y penser", emoji: "☀️" },
      { value: "occasions", label: "Pour les occasions spéciales", emoji: "🥂" },
      { value: "mood_du_jour", label: "Les deux, selon mon mood du jour", emoji: "🦋" },
    ],
  },
  {
    id: "bagues_par_jour",
    bloc: 1,
    blocTitle: "Toi & ton histoire mood",
    type: "single",
    question: "Combien de bagues mood tu portes en moyenne par jour ?",
    options: [
      { value: "1", label: "Une seule", emoji: "🤍" },
      { value: "2_3", label: "2 à 3", emoji: "💕" },
      { value: "4_5", label: "4 à 5", emoji: "✨" },
      { value: "6plus", label: "6 et plus, j'assume 😄", emoji: "💎" },
      { value: "varie", label: "Ça varie tous les jours", emoji: "🦋" },
    ],
  },
  {
    id: "occasions_preferees",
    bloc: 1,
    blocTitle: "Toi & ton histoire mood",
    type: "multi",
    question: "Tes occasions préférées pour porter mood ✨",
    hint: "Plusieurs réponses possibles",
    options: [
      { value: "bureau", label: "Au bureau", emoji: "💼" },
      { value: "weekend", label: "Le weekend", emoji: "🌿" },
      { value: "sport", label: "Au sport", emoji: "🏃‍♀️" },
      { value: "soiree", label: "En soirée", emoji: "🥂" },
      { value: "voyage", label: "En voyage", emoji: "✈️" },
      { value: "mariage", label: "Pour les mariages", emoji: "💒" },
      { value: "anniversaire", label: "Pour mon anniversaire", emoji: "🎂" },
      { value: "fete_meres", label: "Fête des mères", emoji: "🌹" },
      { value: "cadeau_soi", label: "Quand je m'offre un cadeau", emoji: "💝" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // BLOC 2 — Ta collection actuelle
  // ═══════════════════════════════════════════════════════════════
  {
    id: "matieres_possedees",
    bloc: 2,
    blocTitle: "Ta collection actuelle",
    type: "multi",
    question: "Quelles matières as-tu déjà dans ta collection ?",
    hint: "Coche tout ce que tu possèdes",
    options: [
      { value: "acier", label: "Acier", emoji: "⚙️" },
      { value: "titane", label: "Titane", emoji: "✨" },
      { value: "argent", label: "Argent 925", emoji: "🤍" },
      { value: "or_rose", label: "Or rose", emoji: "🌹" },
      { value: "or_jaune", label: "Or jaune", emoji: "☀️" },
      { value: "or_gris", label: "Or gris", emoji: "💎" },
      { value: "email", label: "Émail", emoji: "🎨" },
      { value: "polymere", label: "Polymère", emoji: "🌈" },
      { value: "tantale", label: "Tantale", emoji: "🩶" },
      { value: "alu_couleur", label: "Aluminium coloré", emoji: "🌟" },
      { value: "carbone", label: "Carbone", emoji: "⚫" },
    ],
  },
  {
    id: "largeur",
    bloc: 2,
    blocTitle: "Ta collection actuelle",
    type: "single",
    question: "Ta largeur préférée ?",
    options: [
      { value: "xs", label: "XS — 9mm, fine et délicate", emoji: "🤍" },
      { value: "s", label: "S — 11mm, l'équilibre parfait", emoji: "💕" },
      { value: "l", label: "L — 13mm", emoji: "💫" },
      { value: "melange", label: "Je mélange tout, c'est ça le clic mood", emoji: "🦋" },
    ],
  },
  {
    id: "addons_style",
    bloc: 2,
    blocTitle: "Ta collection actuelle",
    type: "single",
    question: "Ton style d'addons préféré sur la base ?",
    hint: "Ce qui te ressemble le plus au quotidien",
    options: [
      { value: "simple_efficace", label: "Un addon simple et efficace", emoji: "🤍" },
      { value: "2tiers_simple", label: "Deux tiers tout simple", emoji: "💕" },
      { value: "2tiers_medium", label: "Deux tiers avec un medium", emoji: "✨" },
      { value: "2tiers_minis", label: "Deux tiers avec des minis", emoji: "🌸" },
      { value: "que_minis", label: "Que des minis (jusqu'à 6 sur la base !)", emoji: "🦋" },
      { value: "medium_minis", label: "Des mediums et des minis ensemble", emoji: "💎" },
      { value: "que_mediums", label: "Que des mediums", emoji: "💫" },
      { value: "varie", label: "Ça varie selon mon mood du jour", emoji: "🌹" },
    ],
  },
  {
    id: "style",
    bloc: 2,
    blocTitle: "Ta collection actuelle",
    type: "single",
    question: "Ton style mood, c'est plutôt...",
    options: [
      { value: "minimal", label: "Minimal & épuré", emoji: "🤍" },
      { value: "eclat", label: "Éclat & lumière", emoji: "✨" },
      { value: "colore", label: "Coloré & joyeux", emoji: "🌈" },
      { value: "mystere", label: "Mystère & rebelle", emoji: "🖤" },
      { value: "romantique", label: "Romantique & poétique", emoji: "🌹" },
      { value: "mix", label: "Un mix de tout selon les jours", emoji: "🦋" },
    ],
  },
  {
    id: "basique_preferee",
    bloc: 2,
    blocTitle: "Ta collection actuelle",
    type: "text",
    question: "Ta basique préférée — la bague mood que tu portes le plus souvent ?",
    placeholder: "Ex : ma base titane S avec un addon argent serti...",
    optional: true,
  },
  {
    id: "matiere_manquante",
    bloc: 2,
    blocTitle: "Ta collection actuelle",
    type: "text",
    question: "Une matière ou couleur qui te manque dans ta collection ?",
    placeholder: "Ex : un bleu nuit profond, du tantale, un émail coloré...",
    optional: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // BLOC 3 — Tes envies nouveautés
  // ═══════════════════════════════════════════════════════════════
  {
    id: "nouvelle_pepite",
    bloc: 3,
    blocTitle: "Tes envies nouveautés",
    type: "multi",
    question: "Si on créait UNE nouvelle pépite, ça serait plutôt...",
    hint: "Plusieurs choix possibles",
    options: [
      { value: "email_couleur", label: "Un émail coloré inédit", emoji: "🎨" },
      { value: "pierres", label: "Une pièce avec pierres précieuses", emoji: "💎" },
      { value: "matiere_surprise", label: "Une matière qu'on n'a jamais vue", emoji: "✨" },
      { value: "addon_original", label: "Un addon vraiment original", emoji: "🦋" },
      { value: "collab", label: "Une collab avec une artiste", emoji: "🎨" },
      { value: "polymere", label: "Du polymère dans des nouvelles couleurs", emoji: "🌈" },
      { value: "bicolore", label: "Une pièce bicolore (or rose + or gris)", emoji: "🌗" },
    ],
  },
  {
    id: "nouvelle_pepite_libre",
    bloc: 3,
    blocTitle: "Tes envies nouveautés",
    type: "text",
    question: "Une autre idée de nouveauté ? (champ libre)",
    placeholder: "Décris-la nous en quelques mots...",
    optional: true,
  },
  {
    id: "couleurs_vibrent",
    bloc: 3,
    blocTitle: "Tes envies nouveautés",
    type: "multi",
    question: "Les couleurs qui te font vibrer en ce moment 🩵",
    hint: "Coche autant que tu veux",
    options: [
      { value: "blanc_neige", label: "Blanc neige", color: "#FFFFFF" },
      { value: "creme", label: "Crème nacré", color: "#F5E6D3" },
      { value: "rose_poudre", label: "Rose poudré", color: "#E8C5B5" },
      { value: "rose_pale", label: "Rose pâle", color: "#FBC2C2" },
      { value: "rose_fuchsia", label: "Fuchsia", color: "#D63384" },
      { value: "rouge_passion", label: "Rouge passion", color: "#C73E3E" },
      { value: "bordeaux", label: "Bordeaux", color: "#7B1E2B" },
      { value: "orange_corail", label: "Corail", color: "#FF7F50" },
      { value: "orange_brulee", label: "Orange brûlée", color: "#CC5500" },
      { value: "jaune_soleil", label: "Jaune soleil", color: "#F4C430" },
      { value: "jaune_moutarde", label: "Jaune moutarde", color: "#DAA520" },
      { value: "vert_emeraude", label: "Vert émeraude", color: "#2E8B57" },
      { value: "vert_sapin", label: "Vert sapin", color: "#0E4D2D" },
      { value: "vert_menthe", label: "Vert menthe", color: "#98D8C1" },
      { value: "vert_olive", label: "Vert olive", color: "#8B8B3A" },
      { value: "bleu_ciel", label: "Bleu ciel", color: "#87CEEB" },
      { value: "bleu_canard", label: "Bleu canard", color: "#0F7F8A" },
      { value: "bleu_nuit", label: "Bleu nuit", color: "#1B2951" },
      { value: "violet_lavande", label: "Lavande", color: "#B6A4D8" },
      { value: "violet_amethyste", label: "Améthyste", color: "#9966CC" },
      { value: "violet_aubergine", label: "Aubergine", color: "#4B1A4D" },
      { value: "marron_chocolat", label: "Chocolat", color: "#5B3A20" },
      { value: "noir", label: "Noir profond", color: "#0A0A0A" },
      { value: "gris_perle", label: "Gris perle", color: "#C0C0C0" },
      { value: "argent_metal", label: "Argent métallique", color: "#A8A9AD" },
      { value: "champagne", label: "Champagne doré", color: "#E2C792" },
    ],
  },
  {
    id: "pierres_revees",
    bloc: 3,
    blocTitle: "Tes envies nouveautés",
    type: "multi",
    question: "Les pierres qui te font rêver 💎",
    hint: "Plusieurs choix possibles",
    options: [
      { value: "diamant", label: "Diamant blanc", emoji: "💎" },
      { value: "diamant_brun", label: "Diamant brun", emoji: "🤎" },
      { value: "diamant_jaune", label: "Diamant jaune pur", emoji: "💛" },
      { value: "saphir", label: "Saphir bleu", emoji: "🔵" },
      { value: "saphir_rose", label: "Saphir rose", emoji: "🌸" },
      { value: "saphir_mauve", label: "Saphir mauve", emoji: "💜" },
      { value: "rubis", label: "Rubis", emoji: "❤️" },
      { value: "emeraude", label: "Émeraude", emoji: "💚" },
      { value: "topaze", label: "Topaze", emoji: "🩵" },
      { value: "amethyste", label: "Améthyste", emoji: "💜" },
      { value: "zircons", label: "Zircons", emoji: "✨" },
    ],
  },
  {
    id: "zircons_couleur",
    bloc: 3,
    blocTitle: "Tes envies nouveautés",
    type: "multi",
    question: "Si zircons, quelles couleurs te plaisent ?",
    hint: "Plusieurs choix possibles",
    showIf: { questionId: "pierres_revees", valueIncludes: "zircons" },
    optional: true,
    options: [
      { value: "blanc", label: "Blanc / transparent", emoji: "🤍" },
      { value: "rose", label: "Rose", emoji: "🌸" },
      { value: "rouge", label: "Rouge", emoji: "❤️" },
      { value: "bleu", label: "Bleu", emoji: "💙" },
      { value: "vert", label: "Vert", emoji: "💚" },
      { value: "jaune", label: "Jaune", emoji: "💛" },
      { value: "violet", label: "Violet", emoji: "💜" },
      { value: "noir", label: "Noir", emoji: "🖤" },
      { value: "champagne", label: "Champagne", emoji: "🥂" },
      { value: "mix", label: "Un mix coloré", emoji: "🌈" },
    ],
  },
  {
    id: "finition",
    bloc: 3,
    blocTitle: "Tes envies nouveautés",
    type: "single",
    question: "Ta finition préférée ?",
    options: [
      { value: "poli", label: "Poli miroir, éclat maximum", emoji: "✨" },
      { value: "mat", label: "Mat, doux et discret", emoji: "🤍" },
      { value: "brosse", label: "Brossé, texturé", emoji: "🌿" },
      { value: "satine", label: "Satiné, élégant", emoji: "💫" },
      { value: "martele", label: "Martelé, caractère", emoji: "🪨" },
      { value: "mix", label: "Un mix selon les pièces", emoji: "🦋" },
    ],
  },
  {
    id: "sertissage",
    bloc: 3,
    blocTitle: "Tes envies nouveautés",
    type: "single",
    question: "Les pierres serties sur tes bagues...",
    options: [
      { value: "adore", label: "J'adore, plus il y en a mieux c'est", emoji: "💎" },
      { value: "discret", label: "Oui mais discret et délicat", emoji: "✨" },
      { value: "couleur", label: "Oui surtout les pierres colorées", emoji: "🌈" },
      { value: "non", label: "Non, je préfère sans pierres", emoji: "🤍" },
      { value: "depend", label: "Ça dépend de mon mood", emoji: "🦋" },
    ],
  },
  {
    id: "pepite_inedite",
    bloc: 3,
    blocTitle: "Tes envies nouveautés",
    type: "longtext",
    question: "La pépite qu'on n'a pas encore créée et qui te ferait craquer ?",
    hint: "Décris-la nous, même en quelques mots, on lit tout 🌸",
    placeholder: "Ex : un addon avec une pierre en forme de cœur, une base bicolore, une collection inspirée des étoiles...",
    optional: true,
  },
  {
    id: "avis_nouveautes",
    bloc: 3,
    blocTitle: "Tes envies nouveautés",
    type: "longtext",
    question: "Qu'est-ce que tu penses de nos pépites créatives récentes ?",
    hint: "Ce qui t'a marquée, ce que tu as adoré ou moins aimé — sois sincère 💛",
    placeholder: "Ex : j'ai adoré la collection Aura, mais les Yarrow je trouve que...",
    optional: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // BLOC 4 — Les coffrets
  // ═══════════════════════════════════════════════════════════════
  {
    id: "coffret_achete",
    bloc: 4,
    blocTitle: "Les coffrets",
    type: "single",
    question: "Tu as déjà acheté un coffret mood ?",
    options: [
      { value: "oui_moi", label: "Oui, pour moi", emoji: "🎁" },
      { value: "oui_cadeau", label: "Oui, en cadeau", emoji: "💝" },
      { value: "oui_les_deux", label: "Oui, pour moi ET en cadeau", emoji: "✨" },
      { value: "non_interesse", label: "Non, mais ça m'intéresse", emoji: "🌸" },
      { value: "non_jamais", label: "Non, et pas mon truc", emoji: "🤍" },
    ],
  },
  {
    id: "coffret_pour_qui",
    bloc: 4,
    blocTitle: "Les coffrets",
    type: "multi",
    question: "À qui penses-tu d'abord pour offrir un coffret mood ?",
    hint: "Plusieurs réponses possibles",
    options: [
      { value: "maman", label: "Maman", emoji: "🌹" },
      { value: "soeur", label: "Une sœur", emoji: "💕" },
      { value: "amie", label: "Ma meilleure amie", emoji: "🫶🏼" },
      { value: "partenaire", label: "Mon ou ma partenaire", emoji: "❤️" },
      { value: "fille", label: "Ma fille", emoji: "🌸" },
      { value: "belle_mere", label: "Ma belle-mère", emoji: "💐" },
      { value: "collegue", label: "Une collègue chère", emoji: "🌿" },
      { value: "moi", label: "Moi-même 💝", emoji: "✨" },
    ],
  },
  {
    id: "coffret_occasion",
    bloc: 4,
    blocTitle: "Les coffrets",
    type: "multi",
    question: "Pour quelles occasions tu offrirais un coffret ?",
    options: [
      { value: "noel", label: "Noël", emoji: "🎄" },
      { value: "saint_valentin", label: "Saint-Valentin", emoji: "❤️" },
      { value: "fete_meres", label: "Fête des mères", emoji: "🌹" },
      { value: "anniversaire", label: "Un anniversaire", emoji: "🎂" },
      { value: "mariage", label: "Un mariage", emoji: "💒" },
      { value: "naissance", label: "Une naissance", emoji: "🌸" },
      { value: "diplome", label: "Un diplôme / réussite", emoji: "🎓" },
      { value: "juste_parce_que", label: "Juste parce que", emoji: "✨" },
    ],
  },
  {
    id: "coffret_budget",
    bloc: 4,
    blocTitle: "Les coffrets",
    type: "single",
    question: "Budget idéal pour un coffret cadeau ?",
    options: [
      { value: "moins60", label: "Moins de 60 CHF", emoji: "🤍" },
      { value: "60_100", label: "60 à 100 CHF", emoji: "💕" },
      { value: "100_150", label: "100 à 150 CHF", emoji: "🌸" },
      { value: "150_250", label: "150 à 250 CHF", emoji: "✨" },
      { value: "250_500", label: "250 à 500 CHF", emoji: "💎" },
      { value: "500plus", label: "500 CHF et plus", emoji: "👑" },
      { value: "depend", label: "Ça dépend de la personne", emoji: "🦋" },
    ],
  },
  {
    id: "coffret_compo",
    bloc: 4,
    blocTitle: "Les coffrets",
    type: "single",
    question: "La compo idéale d'un coffret, pour toi ?",
    options: [
      { value: "base_2addons", label: "1 base + 2 addons", emoji: "🎁" },
      { value: "base_3_5", label: "1 base + 3 à 5 addons", emoji: "✨" },
      { value: "mini_collection", label: "Une mini collection thématique", emoji: "🌸" },
      { value: "trio", label: "Un trio cohérent (collier + bague + boucles)", emoji: "💎" },
      { value: "surprise", label: "Une surprise box mystère", emoji: "🦋" },
      { value: "personnalise", label: "Quelque chose de personnalisé au prénom", emoji: "💌" },
    ],
  },
  {
    id: "coffret_packaging",
    bloc: 4,
    blocTitle: "Les coffrets",
    type: "multi",
    question: "Le packaging idéal d'un coffret cadeau ?",
    hint: "Plusieurs réponses possibles",
    options: [
      { value: "joli_boite", label: "Une boîte vraiment jolie", emoji: "🎁" },
      { value: "emballage_cadeau", label: "Un emballage cadeau prêt à offrir", emoji: "🎀" },
      { value: "mot_personnalise", label: "Un mot personnalisé glissé dedans", emoji: "💌" },
      { value: "ruban", label: "Un beau ruban", emoji: "🌸" },
      { value: "ecrin_velours", label: "Un écrin velours", emoji: "✨" },
      { value: "carte_origine", label: "Une carte qui raconte l'histoire", emoji: "📖" },
      { value: "minimaliste", label: "Quelque chose de très minimaliste", emoji: "🤍" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // BLOC 5 — La joaillerie
  // ═══════════════════════════════════════════════════════════════
  {
    id: "joaillerie_position",
    bloc: 5,
    blocTitle: "La joaillerie",
    type: "single",
    question: "La joaillerie haute mood, 500.- et plus 💎",
    options: [
      { value: "deja_achete", label: "J'en ai déjà acheté", emoji: "👑" },
      { value: "reve", label: "J'en rêve depuis longtemps", emoji: "✨" },
      { value: "regarde", label: "Je regarde mais c'est cher", emoji: "🌸" },
      { value: "pas_pour_moi", label: "Pas vraiment pour moi", emoji: "🤍" },
    ],
  },
  {
    id: "joaillerie_occasion",
    bloc: 5,
    blocTitle: "La joaillerie",
    type: "multi",
    question: "Pour quelles occasions tu envisagerais une pièce joaillerie ?",
    options: [
      { value: "fiancailles", label: "Fiançailles", emoji: "💍" },
      { value: "anniv_mariage", label: "Anniversaire de mariage", emoji: "💒" },
      { value: "transmission", label: "Transmission (héritage à offrir)", emoji: "👑" },
      { value: "naissance", label: "Naissance d'un enfant", emoji: "🌸" },
      { value: "cadeau_soi", label: "Un cadeau à moi-même", emoji: "💝" },
      { value: "celebration", label: "Une célébration importante", emoji: "🥂" },
      { value: "juste_beau", label: "Juste parce que c'est beau", emoji: "✨" },
    ],
  },
  {
    id: "joaillerie_piece",
    bloc: 5,
    blocTitle: "La joaillerie",
    type: "multi",
    question: "Les pièces joaillerie mood qui te font rêver ?",
    hint: "Plusieurs choix possibles",
    options: [
      { value: "yarrow", label: "Les Yarrow", emoji: "🌾" },
      { value: "medium_serti", label: "Les medium ou mini entièrement sertis", emoji: "💎" },
      { value: "exception", label: "Les pièces d'exception", emoji: "👑" },
      { value: "addon_or_gris", label: "Les addons en or gris", emoji: "🌟" },
      { value: "tresors_neree", label: "La collection Les Trésors de Nérée", emoji: "🌊" },
      { value: "coffret_lanieka", label: "Le coffret Lanieka", emoji: "🎁" },
      { value: "base_sertie", label: "Les bases entièrement serties", emoji: "✨" },
      { value: "mille_une_nuits", label: "Le 1001 Nuits", emoji: "🌙" },
      { value: "rosas_ouros", label: "Le Rosas de Ouros", emoji: "🌹" },
    ],
  },
  {
    id: "joaillerie_piece_autre",
    bloc: 5,
    blocTitle: "La joaillerie",
    type: "text",
    question: "Une autre pièce joaillerie qui te fait rêver ?",
    placeholder: "Ex : un solitaire avec un saphir rose, une bague mood avec diamant brun...",
    optional: true,
  },
  {
    id: "piece_unique",
    bloc: 5,
    blocTitle: "La joaillerie",
    type: "single",
    question: "Une pièce unique, créée rien que pour toi, ça te tente ?",
    options: [
      { value: "absolument", label: "Oui absolument, c'est mon rêve", emoji: "✨" },
      { value: "si_pas_cher", label: "Oui, si le prix reste raisonnable", emoji: "💕" },
      { value: "peut_etre", label: "Peut-être, à voir le projet", emoji: "🌸" },
      { value: "collection", label: "Non, je préfère les collections", emoji: "🤍" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // BLOC 6 — Tes habitudes d'achat
  // ═══════════════════════════════════════════════════════════════
  {
    id: "canal_achat",
    bloc: 6,
    blocTitle: "Tes habitudes d'achat",
    type: "multi",
    question: "Tu achètes Mood plutôt où ?",
    hint: "Plusieurs réponses possibles",
    options: [
      { value: "site", label: "Sur le site yourmood.net", emoji: "💻" },
      { value: "boutique", label: "En boutique physique", emoji: "🏪" },
      { value: "telephone", label: "Par téléphone avec une vendeuse", emoji: "📞" },
      { value: "insta_dm", label: "Par DM Instagram", emoji: "📷" },
      { value: "evenement", label: "Sur un événement ou un stand", emoji: "🎪" },
    ],
  },
  {
    id: "frequence_achat",
    bloc: 6,
    blocTitle: "Tes habitudes d'achat",
    type: "single",
    question: "À quelle fréquence tu t'offres une nouvelle pépite mood ?",
    options: [
      { value: "souvent", label: "Plusieurs fois par mois", emoji: "💎" },
      { value: "mensuel", label: "Environ une fois par mois", emoji: "✨" },
      { value: "trimestre", label: "Quelques fois par an", emoji: "🌸" },
      { value: "annee", label: "Une à deux fois par an", emoji: "💕" },
      { value: "rare", label: "Plus rarement, pour les grandes occasions", emoji: "🤍" },
    ],
  },
  {
    id: "panier_moyen",
    bloc: 6,
    blocTitle: "Tes habitudes d'achat",
    type: "slider",
    question: "Ton panier moyen par commande mood ?",
    hint: "Glisse le curseur sur ton estimation 🌟",
    sliderMin: 50,
    sliderMax: 1000,
    sliderStep: 10,
    sliderUnit: "CHF",
    sliderLabels: { min: "50 CHF", max: "1000+ CHF" },
  },
  {
    id: "prix_compo_juste",
    bloc: 6,
    blocTitle: "Tes habitudes d'achat",
    type: "slider",
    question: "Selon toi, le prix juste pour une compo mood complète (1 base + 3 addons) ?",
    hint: "On veut vraiment ton sentiment honnête",
    sliderMin: 100,
    sliderMax: 800,
    sliderStep: 10,
    sliderUnit: "CHF",
    sliderLabels: { min: "100 CHF", max: "800+ CHF" },
  },
  {
    id: "motivation_rachat",
    bloc: 6,
    blocTitle: "Tes habitudes d'achat",
    type: "multi",
    question: "Pourquoi tu reviens chez mood ? 💛",
    hint: "Plusieurs réponses possibles",
    options: [
      { value: "qualite", label: "La qualité des bijoux", emoji: "💎" },
      { value: "design", label: "Le design unique et reconnaissable", emoji: "✨" },
      { value: "variete", label: "La variété (toujours envie d'une nouvelle compo)", emoji: "🌈" },
      { value: "concept", label: "Le concept de bagues interchangeables", emoji: "🔄" },
      { value: "communaute", label: "La communauté Mood Lovers", emoji: "🫶🏼" },
      { value: "fabrication", label: "La fabrication suisse / artisanale", emoji: "🇨🇭" },
      { value: "garantie", label: "La garantie à vie", emoji: "🛡️" },
      { value: "service", label: "Le service client / les boutiques", emoji: "💝" },
      { value: "histoire", label: "L'histoire de la marque", emoji: "📖" },
      { value: "addictif", label: "C'est addictif, j'en veux toujours plus 😄", emoji: "🌹" },
    ],
  },
  {
    id: "frein_achat",
    bloc: 6,
    blocTitle: "Tes habitudes d'achat",
    type: "multi",
    question: "Et qu'est-ce qui te freine parfois ?",
    hint: "On veut comprendre — c'est ce qui nous permet d'évoluer 🌸",
    optional: true,
    options: [
      { value: "prix", label: "Le prix sur certaines pièces", emoji: "💰" },
      { value: "deja_assez", label: "J'ai déjà tout ce qu'il me faut", emoji: "🤍" },
      { value: "delai", label: "Les délais de fabrication", emoji: "⏰" },
      { value: "stock", label: "Les ruptures de stock", emoji: "📦" },
      { value: "trop_choix", label: "Trop de choix, je n'arrive pas à décider", emoji: "🌀" },
      { value: "pas_nouveau", label: "Pas assez de nouveautés à mon goût", emoji: "🌸" },
      { value: "site", label: "Quelque chose qui me gêne sur le site", emoji: "💻" },
      { value: "rien", label: "Rien ne me freine ❤️", emoji: "✨" },
    ],
  },
  {
    id: "story_achat",
    bloc: 6,
    blocTitle: "Tes habitudes d'achat",
    type: "longtext",
    question: "Ton souvenir d'achat mood le plus marquant ?",
    hint: "Un moment, une émotion, une rencontre en boutique, un cadeau reçu...",
    placeholder: "Ex : ma première bague mood offerte par ma sœur, ou la fois où Stéphanie en personne m'a conseillée...",
    optional: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // BLOC 7 — Comment tu nous as connu(e)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "decouverte_marque",
    bloc: 7,
    blocTitle: "Comment tu nous as connu(e)",
    type: "multi",
    question: "Comment tu as connu Mood pour la première fois ?",
    hint: "Plusieurs réponses possibles",
    options: [
      { value: "instagram", label: "Instagram", emoji: "📷" },
      { value: "facebook", label: "Facebook", emoji: "💙" },
      { value: "tiktok", label: "TikTok", emoji: "🎵" },
      { value: "pinterest", label: "Pinterest", emoji: "📌" },
      { value: "google", label: "Recherche Google", emoji: "🔍" },
      { value: "boutique", label: "En passant devant une boutique", emoji: "🏪" },
      { value: "amie", label: "Une amie / proche m'en a parlé", emoji: "🫶🏼" },
      { value: "pub", label: "Une pub en ligne", emoji: "📣" },
      { value: "presse", label: "Dans la presse / magazine", emoji: "📰" },
      { value: "influenceuse", label: "Une influenceuse en parlait", emoji: "💫" },
      { value: "evenement", label: "Un événement / salon", emoji: "🎪" },
      { value: "autre", label: "Autre", emoji: "✨" },
    ],
  },
  {
    id: "reseaux_suivis",
    bloc: 7,
    blocTitle: "Comment tu nous as connu(e)",
    type: "multi",
    question: "Tu suis Mood sur quels réseaux ?",
    options: [
      { value: "instagram", label: "Instagram", emoji: "📷" },
      { value: "facebook", label: "Facebook", emoji: "💙" },
      { value: "tiktok", label: "TikTok", emoji: "🎵" },
      { value: "pinterest", label: "Pinterest", emoji: "📌" },
      { value: "youtube", label: "YouTube", emoji: "📺" },
      { value: "newsletter", label: "Newsletter email", emoji: "📧" },
      { value: "aucun", label: "Aucun pour l'instant", emoji: "🌱" },
    ],
  },
  {
    id: "stories_insta",
    bloc: 7,
    blocTitle: "Comment tu nous as connu(e)",
    type: "single",
    question: "Nos stories Instagram, tu les regardes ?",
    options: [
      { value: "tout", label: "Je suis tout, j'adore", emoji: "❤️" },
      { value: "temps_en_temps", label: "De temps en temps", emoji: "✨" },
      { value: "rarement", label: "Rarement", emoji: "🌸" },
      { value: "jamais", label: "Jamais — pas trop Insta", emoji: "🤍" },
    ],
  },
  {
    id: "emails_klaviyo",
    bloc: 7,
    blocTitle: "Comment tu nous as connu(e)",
    type: "single",
    question: "Nos emails newsletter, qu'en penses-tu ?",
    hint: "Sois franche, on veut vraiment savoir 💛",
    options: [
      { value: "adore", label: "J'adore et j'ouvre tout", emoji: "💌" },
      { value: "ouvre_parfois", label: "J'ouvre parfois selon le sujet", emoji: "✨" },
      { value: "trop_mails", label: "Trop de mails à mon goût", emoji: "📭" },
      { value: "pas_recoit", label: "Je ne crois pas en recevoir", emoji: "🌱" },
      { value: "desabonnee", label: "Je me suis désabonnée", emoji: "🤍" },
    ],
  },
  {
    id: "visite_boutique",
    bloc: 7,
    blocTitle: "Comment tu nous as connu(e)",
    type: "single",
    question: "Tu es déjà allée dans une boutique mood ?",
    options: [
      { value: "souvent", label: "Oui, j'y vais souvent", emoji: "🏪" },
      { value: "quelquefois", label: "Oui, quelques fois", emoji: "✨" },
      { value: "une_fois", label: "Oui, une fois", emoji: "🌸" },
      { value: "jamais_envie", label: "Jamais mais ça me tenterait", emoji: "💕" },
      { value: "jamais", label: "Jamais et c'est OK", emoji: "🤍" },
    ],
  },
  {
    id: "entourage_mood",
    bloc: 7,
    blocTitle: "Comment tu nous as connu(e)",
    type: "single",
    question: "Combien de personnes autour de toi portent du mood ?",
    options: [
      { value: "0", label: "Personne, je suis la seule 😉", emoji: "🌸" },
      { value: "1_2", label: "1 ou 2 personnes", emoji: "💕" },
      { value: "3_5", label: "3 à 5 personnes", emoji: "✨" },
      { value: "6_10", label: "6 à 10 personnes", emoji: "💎" },
      { value: "10plus", label: "Plus de 10 — c'est viral autour de moi 🦋", emoji: "🌹" },
    ],
  },
  {
    id: "parrainage",
    bloc: 7,
    blocTitle: "Comment tu nous as connu(e)",
    type: "single",
    question: "Tu as déjà fait découvrir Mood à quelqu'un ?",
    options: [
      { value: "souvent", label: "Oui, souvent — je suis une serial moodarraine 😄", emoji: "🫶🏼" },
      { value: "quelquefois", label: "Oui, quelques fois", emoji: "💕" },
      { value: "rarement", label: "Rarement", emoji: "🌸" },
      { value: "jamais", label: "Jamais encore", emoji: "🌱" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // BLOC 8 — Notre site, nos photos, notre service
  // ═══════════════════════════════════════════════════════════════
  {
    id: "note_site",
    bloc: 8,
    blocTitle: "Notre site, nos photos, notre service",
    type: "rating",
    question: "Tu donnes combien d'étoiles à yourmood.net ? 💻",
    hint: "Touche les étoiles pour noter",
    ratingMax: 5,
  },
  {
    id: "note_photos",
    bloc: 8,
    blocTitle: "Notre site, nos photos, notre service",
    type: "rating",
    question: "Et à nos photos produit ? 📸",
    ratingMax: 5,
  },
  {
    id: "note_packaging",
    bloc: 8,
    blocTitle: "Notre site, nos photos, notre service",
    type: "rating",
    question: "Notre packaging (si tu l'as reçu) ? 🎁",
    hint: "Sinon passe à la suivante",
    ratingMax: 5,
    optional: true,
  },
  {
    id: "note_service_client",
    bloc: 8,
    blocTitle: "Notre site, nos photos, notre service",
    type: "rating",
    question: "Notre service client (si tu l'as testé) ? 💝",
    hint: "Sinon passe à la suivante",
    ratingMax: 5,
    optional: true,
  },
  {
    id: "site_aime",
    bloc: 8,
    blocTitle: "Notre site, nos photos, notre service",
    type: "multi",
    question: "Ce que tu aimes le plus sur notre site ?",
    options: [
      { value: "photos", label: "Les photos", emoji: "📷" },
      { value: "compo", label: "Le configurateur de compo", emoji: "🔄" },
      { value: "descriptions", label: "Les descriptions produits", emoji: "📖" },
      { value: "blog", label: "Le blog / histoires de la marque", emoji: "💌" },
      { value: "navigation", label: "La navigation simple", emoji: "🧭" },
      { value: "filtres", label: "Les filtres par matière/couleur", emoji: "🎨" },
      { value: "avis", label: "Les avis clients", emoji: "⭐" },
      { value: "compte", label: "Mon espace personnel", emoji: "👤" },
      { value: "mobile", label: "L'expérience sur mobile", emoji: "📱" },
    ],
  },
  {
    id: "site_changerait",
    bloc: 8,
    blocTitle: "Notre site, nos photos, notre service",
    type: "longtext",
    question: "Qu'est-ce que tu changerais sur notre site ?",
    hint: "Toute idée est précieuse — sois franche 💛",
    placeholder: "Ex : j'aimerais voir la bague portée, mieux comprendre les tailles, plus de vidéos, un truc plus rapide...",
    optional: true,
  },
  {
    id: "photos_envie",
    bloc: 8,
    blocTitle: "Notre site, nos photos, notre service",
    type: "multi",
    question: "Tu aimerais voir plus de quel type de photos ?",
    hint: "Pour qu'on sache où concentrer nos efforts visuels",
    options: [
      { value: "portees", label: "Plus de photos portées (sur la main)", emoji: "✋" },
      { value: "details", label: "Plus de gros plans détail", emoji: "🔍" },
      { value: "compos", label: "Plus d'exemples de compos complètes", emoji: "🎨" },
      { value: "lifestyle", label: "Plus de photos lifestyle / ambiance", emoji: "🌸" },
      { value: "ateliers", label: "Plus d'images de l'atelier / fabrication", emoji: "🛠️" },
      { value: "videos", label: "Plus de vidéos courtes", emoji: "🎥" },
      { value: "client", label: "Plus de photos de vraies clientes", emoji: "💕" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // BLOC 9 — L'âme de Mood (ludique / émotionnel)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "thermometre_mood",
    bloc: 9,
    blocTitle: "L'âme de Mood",
    type: "gauge",
    question: "À quel point tu aimes Mood ? 💖",
    hint: "Glisse le thermomètre... sois honnête !",
    sliderLabels: { min: "Tiède", max: "Folle amoureuse" },
  },
  {
    id: "podium_collections",
    bloc: 9,
    blocTitle: "L'âme de Mood",
    type: "rank",
    question: "Classe tes 3 collections préférées sur le podium 🏆",
    hint: "Touche les flèches pour réorganiser. Les 3 premières comptent.",
    rankTopN: 3,
    optional: true,
    options: [
      { value: "aura", label: "Aura", emoji: "✨" },
      { value: "star", label: "Star", emoji: "⭐" },
      { value: "emotion", label: "Emotion", emoji: "💕" },
      { value: "signature", label: "Signature", emoji: "💍" },
      { value: "eclipse", label: "Eclipse", emoji: "🌙" },
      { value: "heritage", label: "Heritage", emoji: "👑" },
      { value: "blue_series", label: "Blue Series", emoji: "💙" },
      { value: "entrelacs", label: "Entrelacs", emoji: "🌹" },
      { value: "iconiques", label: "Iconiques", emoji: "💎" },
      { value: "droits_femmes", label: "Droits des femmes", emoji: "🫶🏼" },
    ],
  },
  {
    id: "saison_mood",
    bloc: 9,
    blocTitle: "L'âme de Mood",
    type: "single",
    question: "Si Mood était une saison, ce serait...",
    options: [
      { value: "printemps", label: "Le printemps — renaissance et fraîcheur", emoji: "🌸" },
      { value: "ete", label: "L'été — lumière et joie", emoji: "☀️" },
      { value: "automne", label: "L'automne — poésie et chaleur", emoji: "🍂" },
      { value: "hiver", label: "L'hiver — éclat et mystère", emoji: "❄️" },
    ],
  },
  {
    id: "element_mood",
    bloc: 9,
    blocTitle: "L'âme de Mood",
    type: "single",
    question: "Si Mood était un élément...",
    options: [
      { value: "feu", label: "Le feu — passion et éclat", emoji: "🔥" },
      { value: "eau", label: "L'eau — fluidité et profondeur", emoji: "💧" },
      { value: "terre", label: "La terre — ancrage et authenticité", emoji: "🌿" },
      { value: "air", label: "L'air — légèreté et liberté", emoji: "🦋" },
    ],
  },
  {
    id: "mood_personnalite",
    bloc: 9,
    blocTitle: "L'âme de Mood",
    type: "text",
    question: "Si Mood était une personnalité, qui ?",
    hint: "Une artiste, une icône, un personnage — ce qui te vient",
    placeholder: "Ex : Audrey Hepburn, Frida Kahlo, ma grand-mère...",
    optional: true,
  },

  // ═══════════════════════════════════════════════════════════════
  // BLOC 10 — Ta pépite rêvée + cadeau
  // ═══════════════════════════════════════════════════════════════
  {
    id: "piece_revee",
    bloc: 10,
    blocTitle: "Ta pépite rêvée",
    type: "longtext",
    question: "Décris-nous la pièce mood de tes rêves 💌",
    hint: "Imagine qu'on peut la créer pour toi. Qu'est-ce que ce serait ?",
    placeholder: "Ex : une bague qui change de couleur selon la lumière, une compo qui raconte mon histoire, un coffret avec ma pierre de naissance...",
    optional: true,
  },
  {
    id: "contact",
    bloc: 10,
    blocTitle: "Ta pépite rêvée",
    type: "contact",
    question: "Ton prénom et ton email pour recevoir ton bon 20.- ✨",
    hint: "Promis, zéro spam, juste les pépites créatives.",
  },
];
