import { NextResponse } from "next/server";

// === PROMPTS FR ORIGINAUX D'AMILA ===
// Extraits depuis les archives Claude /Users/amila/.claude/projects/
// Lignes : 17312 (Terre d'ombre), 17522 (Terre Olive), 17558 (Tropical),
// 17661 (Sakura), 17838 (Pur White), 18379 (Zanzibar), 18459 (Béton),
// 18494 (Pastel), 18517 (In the mood for), 18543 (Lifestyle).
//
// Cette endpoint sert les VERSIONS ORIGINALES écrites par Amila en français.
// Différent du code de l'app qui utilise les versions anglaises traduites/enrichies.

type Prompts = {
  label: string;
  porte: string;      // Prompt bague portée
  ambiance: string;   // Prompt bague d'ambiance / objet
  porte_homme?: string; // Variante homme (si Amila l'a livrée)
};

const PROMPTS_FR_AMILA: Record<string, Prompts> = {
  "terre-olive": {
    label: "Terre Olive",
    porte: `femme asiatique, longs cheveux noirs lisses. Photographie éditoriale minimaliste de bijoux de luxe, ambiance très épurée et sophistiquée. Lumière naturelle directionnelle de fin de journée créant des ombres profondes et graphiques. Esthétique inspirée de Jacquemus, Bottega Veneta et campagnes joaillerie haut de gamme. Composition ultra minimaliste avec beaucoup d'espace vide, focus total sur le bijou. Atmosphère calme, organique, moderne et luxueuse. Rendu photo éditorial premium, ultra réaliste, lumière chaude et cinématographique, profondeur de champ douce, détails précieux, esthétique luxe silencieux et contemporain. Tenue : blouse très fluide (comme un foulard) avec mouvement en coton blanc, épaule dénudée, manucure naturel très soignée. Zoom sur la bague.`,
    ambiance: `Photographie éditoriale minimaliste de bijoux de luxe, ambiance très épurée et sophistiquée. Fond uni texturé dans des tons olive doux, beige sable ou ivoire chaud. Lumière naturelle directionnelle de fin de journée créant des ombres profondes et graphiques. Esthétique inspirée de Jacquemus, Bottega Veneta et campagnes joaillerie haut de gamme. Bijoux mis en scène avec très peu d'éléments : une feuille floue, une ombre végétale, une surface mate, un reflet dans l'eau ou un simple jeu de lumière. Composition ultra minimaliste avec beaucoup d'espace vide, focus total sur le bijou. Atmosphère calme, organique, moderne et luxueuse. Rendu photo éditorial premium, ultra réaliste, lumière chaude et cinématographique, profondeur de champ douce, détails précieux, esthétique luxe silencieux et contemporain.`,
  },
  "tropical": {
    label: "Tropical",
    porte: `Photographie macro éditoriale de bijoux portés, mise en scène végétale tropicale sombre et satinée. Tons vert forêt, olive foncé, noir végétal et reflets dorés subtils. Lumière dramatique et directionnelle créant des zones d'ombre intenses et des éclats lumineux précis sur le bijou.`,
    ambiance: `Photographie macro éditoriale de bijoux de luxe posés sur de grandes feuilles tropicales sombres et satinées. Ambiance végétale profonde, élégante et mystérieuse. Tons vert forêt, olive foncé, noir végétal et reflets dorés subtils. Lumière dramatique et directionnelle créant des zones d'ombre intenses et des éclats lumineux précis sur le bijou. Atmosphère luxueuse et organique, inspirée des campagnes haute joaillerie contemporaines. Rendu ultra réaliste, esthétique premium et sophistiquée, profondeur de champ douce, détails précieux.`,
  },
  "sakura": {
    label: "Sakura",
    porte: `Photographie macro éditoriale de luxe d'une bague portée sur une main féminine élégante, focus très net et rapproché sur la bague. Main délicatement posée près d'une épaule dénudée, peau légèrement bronzée et lumineuse. Robe fluide rose clair en tissu léger et aérien, mouvement subtil du textile dans une ambiance printanière douce et sophistiquée. Lumière naturelle du matin, chaude et délicate, créant de fines ombres de branches de sakura sur la peau et le décor. Palette pastel raffinée : rose poudré, beige chaud, blanc crème et reflets dorés subtils. Composition minimaliste et haut de gamme inspirée de Jacquemus et des campagnes joaillerie luxe contemporaines.`,
    ambiance: `Photographie éditoriale de luxe minimaliste inspirée de Jacquemus et des campagnes mode haut de gamme contemporaines. Univers printanier épuré, moderne et lumineux. Lumière douce du matin entrant latéralement, créant de délicates ombres de branches de sakura projetées sur les surfaces et la peau. Palette raffinée et naturelle : blanc crème, beige chaud, rose poudré très subtil, pierre claire et reflets dorés doux. Composition ultra minimaliste avec beaucoup d'espace négatif, architecture méditerranéenne contemporaine, matières nobles et textures mates sophistiquées. Atmosphère calme, aérienne et premium, mélange de poésie printanière et de luxe silencieux. Esthétique propre, artistique et haut de gamme, sans surcharge visuelle. Rendu ultra réaliste, lumière cinématographique naturelle, ombres graphiques délicates, style magazine mode luxe contemporain.`,
  },
  "pur-white": {
    label: "Pur White (Joaillerie)",
    porte: `Photographie éditoriale de haute joaillerie portée, lumière cristalline et aérienne. Main féminine élégante, peau lumineuse. Fond blanc glacé ou gris perle très clair. Ambiance pure, minimaliste, premium. Bijou en focus, éclats prismatiques et reflets diamantés.`,
    ambiance: `Photographie éditoriale de haute joaillerie ultra lumineuse et cristalline, inspirée des campagnes Swarovski et de la photographie diamant contemporaine. Bijoux photographiés sur fond blanc glacé ou gris perle très clair, dans une ambiance pure, aérienne et minimaliste. Lumière naturelle intense et directionnelle créant des éclats prismatiques, reflets diamantés et arcs-en-ciel subtils sur les surfaces polies. Esthétique luxe pur, élégante et cristalline, sans surcharge visuelle. Composition épurée, focus total sur la pureté du bijou.`,
  },
  "zanzibar": {
    label: "Zanzibar",
    porte: `Photo lifestyle minimaliste et élégante, lumière naturelle douce, femme portant une chemise blanche oversize, ambiance éditoriale moderne, cadrage rapproché sur les mains et poignets, pose naturelle et détendue, fond clair et épuré, profondeur de champ légère, tons chauds et lumineux, style premium, esthétique simple et raffinée, rendu photoréaliste, très peu d'accessoires, ambiance douce et féminine.`,
    ambiance: `Décor photo minimaliste blanc, formes organiques douces, lumière naturelle diffuse, ambiance luxe épurée, fond propre et aérien, quelques courbes inspirées des vagues, ombres légères, style studio premium, très peu d'accessoires, composition simple et élégante, rendu photoréaliste.`,
  },
  "beton": {
    label: "Béton",
    porte: `Editorial fashion lifestyle, femme élégante style urbain chic, top noir minimaliste, lumière douce et sombre, ambiance luxe moderne, accumulation de bijoux fins et audacieux, pose naturelle miroir ou cadrage rapproché, esthétique Pinterest premium, rendu cinématographique photoréaliste, fond discret et flou, style sophistiqué et tendance.`,
    porte_homme: `Editorial masculin minimaliste, lumière naturelle tamisée, ambiance moody et élégante, vêtements oversize texturés dans des tons terreux et neutres, cadrage focus mains et torse, esthétique luxe contemporaine, style urbain raffiné, rendu cinématographique photoréaliste, fond épuré sombre, attitude calme et confiante.`,
    ambiance: `Studio photo minimaliste sombre, textures métalliques organiques et sculptées à la main, inspiration roche brute et matière fondue, fond béton anthracite texturé, lumière cinématographique douce, ambiance luxe artisanale, esthétique moderne et minérale, rendu premium photoréaliste, composition sobre et élégante.`,
  },
  "pastel": {
    label: "Pastel",
    porte: `Photo lifestyle urbaine moderne, cadrage dynamique en perspective avec les poings tendus vers l'objectif, focus net sur les mains au premier plan et arrière-plan volontairement flou, profondeur de champ très faible avec bokeh doux, attitude confiante et playful, lumière naturelle douce légèrement cinématographique, ambiance streetwear minimaliste, hoodie oversize pastel, esthétique moderne et tendance, style éditorial Pinterest premium, composition immersive avec effet de profondeur, rendu photoréaliste, ombres douces, ambiance jeune et cool, focus principal sur les mains et les détails au premier plan, arrière-plan flou artistique.`,
    ambiance: `Photo macro produit haut de gamme, bague principale parfaitement nette et centrée au premier plan, arrière-plan composé uniquement d'anneaux colorés reprenant exactement la même couleur, la même texture, la même taille et la même largeur que l'anneau central de la bague principale, sans les bordures métalliques visibles. Les anneaux en arrière-plan sont disposés aléatoirement de façon naturelle et harmonieuse, certains debout, certains couchés, créant une composition organique et équilibrée. Profondeur de champ très faible avec arrière-plan fortement flou, bokeh doux et crémeux, focus ultra précis sur la bague centrale, lumière studio diffuse et chaleureuse, ambiance minimaliste premium, surface en bois clair naturel, style éditorial luxe moderne, rendu photoréaliste, éclairage cinématographique doux, objectif macro 85mm, f/2.8.`,
  },
  "in-the-mood-for": {
    label: "In the mood for",
    porte: `Photo lifestyle éditoriale moderne, belle femme bronzée, ongles manucurés forme amande avec French élégante, petit tatouage discret au doigt, poings tendus vers l'objectif devant le visage pour le cacher partiellement, focus ultra net sur les mains au premier plan, visage et arrière-plan fortement flous, profondeur de champ très faible avec bokeh doux et crémeux, lumière naturelle diffuse et chaleureuse, ambiance cosy et premium, vêtements doux beige nude, esthétique minimaliste et féminine, pose confiante et moderne, style Pinterest luxe, rendu photoréaliste, ombres délicates, cadrage immersif centré sur les mains, objectif portrait 85mm, ambiance douce et tendance.`,
    porte_homme: `Photo lifestyle éditoriale moderne, homme bronzé, poings tendus vers l'objectif devant le visage pour le cacher partiellement, focus ultra net sur les mains au premier plan, visage et arrière-plan fortement flous, profondeur de champ très faible avec bokeh doux et crémeux, lumière naturelle diffuse et chaleureuse, ambiance cosy et premium, vêtements doux beige nude, esthétique minimaliste, pose confiante et moderne, style Pinterest luxe, rendu photoréaliste, ombres délicates, cadrage immersif centré sur les mains, objectif portrait 85mm, ambiance douce et tendance. (Pas de manucure.)`,
    ambiance: `Photo produit lifestyle premium, décor minimaliste chaleureux et élégant, surface beige clair, arrière-plan textile crème légèrement flou, ambiance cozy et luxe moderne, lumière naturelle douce et chaude, ombres délicates, profondeur de champ très faible, style Pinterest éditorial, textures douces et raffinées, esthétique minimaliste féminine, composition épurée et harmonieuse, rendu photoréaliste, arrière-plan flou crémeux, ambiance soft luxury contemporaine.`,
  },
  "lifestyle": {
    label: "Lifestyle",
    porte: `Photo lifestyle spontanée prise à la main, main tendue vers le paysage ou l'environnement, focus naturel sur la main au premier plan avec arrière-plan vivant et immersif, ambiance authentique "daily life", lumière naturelle réelle, style photo souvenir premium, esthétique Pinterest lifestyle, cadrage simple et spontané comme une photo prise sur le moment avec smartphone, profondeur légère naturelle, environnement légèrement flou mais reconnaissable, rendu photoréaliste, ambiance voyage et moments de vie, composition décontractée et organique, lumière extérieure réaliste, style non studio, sensation de vrai instant capturé.`,
    ambiance: `Photo naturelle non studio, lumière du jour réelle, décor vivant en arrière-plan, ambiance spontanée et authentique, rendu simple et réaliste, style souvenir de voyage.`,
  },
  "terre-dombre": {
    label: "Terre d'ombre",
    porte: `Femme à la peau bronzée, épaule dénudée. Lumière dorée de fin de journée entrant latéralement, ombres profondes et graphiques projetées sur les surfaces et sur la peau. Ambiance cinématographique et éditoriale haut de gamme, esthétique mode type Jacquemus ou campagne de luxe. Contraste fort entre lumière chaude et obscurité, atmosphère élégante, mystérieuse et artisanale. Tons terracotta, beige, brun chaud et noir profond. Lumière dramatique, composition épurée et sophistiquée.`,
    ambiance: `Architecture méditerranéenne contemporaine, murs en terre cuite et plâtre chaud texturé, volumes architecturaux sculpturaux simples (coin, marche, fragment d'arche, niche, rebord en argile brute). Lumière dorée de fin d'après-midi entrant latéralement (angle bas ~25-40°), chaude et dramatique — comme la dernière heure avant le coucher de soleil en Provence ou dans une cour marocaine. Ombres profondes, graphiques et marquées projetées sur les surfaces (signature Jacquemus). Fort contraste entre les zones lumineuses chaudes et les zones d'ombre profondes. Palette : terracotta, beige sable, sienne brûlée, brun chaud, ocre, cuivre — avec du noir profond ou du brun foncé dans les ombres. Ambiance cinématographique, éditoriale, élégante, mystérieuse, artisanale, brute et raffinée. Inspiration : campagne d'été Jacquemus, éditorial Loewe earth-tone, Bottega Veneta minimaliste sculptural, luxe méditerranéen brut.`,
  },
  "riviera": {
    label: "Riviera",
    porte: `Photographie éditoriale estivale haut de gamme inspirée des campagnes resort de luxe et beauté méditerranéenne. Femme élégante DANS UNE PISCINE en pierre claire, peau bronzée satinée par le soleil, maillot minimaliste chic. Eau turquoise cristalline créant des reflets mouvants et lumineux sur la peau et les surfaces minérales. Prise de vue en plongée, composition épurée et sophistiquée, ambiance calme et sensuelle. Lumière naturelle forte de milieu de journée, ombres nettes et graphiques, esthétique luxe silencieux. Palette douce et solaire : beige pierre chaude, turquoise pâle, peau dorée et blanc crème. Filtre éditorial premium légèrement chaud et désaturé, contraste doux, grain subtil type photographie argentique luxe, rendu lumineux et cinématographique inspiré de Jacquemus, campaigns resortwear et magazines mode haut de gamme. Atmosphère minimaliste, méditerranéenne et exclusive, ultra réaliste, élégante et moderne.`,
    ambiance: `Univers estival méditerranéen luxueux — sable fin sculpté par le vent, eau turquoise cristalline, pierre claire texturée (calcaire, travertin), lumière dorée intense. Ambiance chic balnéaire haut de gamme. Soleil méditerranéen direct en plein midi créant des ombres graphiques marquées sur les surfaces. Reflets aqua mouvants de l'eau de la piscine projetant des motifs lumineux sur la pierre et la peau. Palette : beige sable chaud, crème solaire, turquoise pâle, or chaud, peau caramel bronzée, blanc minéral — palette solaire douce et sophistiquée. Atmosphère : luxe silencieux, calme, estivale, raffinée, sensuelle, vacances méditerranéennes exclusives. Inspiration : campagne Cartier Riviera, été Jacquemus, éditorial resort luxe contemporain, magazine mode haut de gamme. Touches déco subtiles (1-2 max par photo) : sable sculpté par le vent, bord de piscine avec reflets aqua, surface en pierre claire, gouttes d'eau sur la peau. Jamais surchargé. Composition ultra épurée.`,
  },
  "bora-bora": {
    label: "Bora Bora",
    porte: `Photographie éditoriale estivale haut de gamme inspirée des campagnes resort de luxe et beauté méditerranéenne. Femme élégante DANS UNE PISCINE en pierre claire, piscine fond ocre, peau bronzée satinée par le soleil, maillot minimaliste chic rose clair ou brun. Eau créant des reflets mouvants et lumineux sur la peau et les surfaces minérales. Prise de vue en plongée, composition épurée et sophistiquée, ambiance calme et sensuelle. Lumière chaude naturelle forte de fin de journée, ombres nettes et graphiques, esthétique luxe silencieux. Palette douce et solaire : beige pierre chaude, rose pâle, peau dorée et beige crème. Filtre éditorial premium légèrement chaud et désaturé, contraste doux, grain subtil type photographie argentique luxe, rendu lumineux et cinématographique inspiré de Jacquemus, campaigns resortwear et magazines mode haut de gamme. Atmosphère minimaliste, méditerranéenne et exclusive, ultra réaliste, élégante et moderne.`,
    ambiance: `Univers estival méditerranéen luxueux — sable fin rose orangé sculpté par le vent, lumière dorée intense. Ambiance chic balnéaire haut de gamme. Soleil méditerranéen direct en plein après-midi créant des ombres graphiques marquées sur les surfaces. Reflets aqua mouvants de l'eau de la mer projetant des motifs lumineux orangé sur la pierre et la peau. Palette : ocre, rose clair, sable chaud, crème solaire, rose pâle, or chaud, peau caramel bronzée, beige minéral — palette solaire douce et sophistiquée. Atmosphère : luxe silencieux, calme, estivale, raffinée, sensuelle, vacances méditerranéennes exclusives. Inspiration : campagne Cartier Riviera, été Jacquemus, éditorial resort luxe contemporain, magazine mode haut de gamme. Touches déco subtiles (1-2 max par photo) : sable sculpté par le vent, ombre de palmier. Jamais surchargé. Composition ultra épurée.`,
  },
  "black-joaillerie": {
    label: "Black Joaillerie",
    porte: `Photographie éditoriale haute couture portée, ambiance très luxueuse, dramatique et sophistiquée. Femme élégante photographiée dans un STUDIO SOMBRE ET MINIMALISTE, peau profondément lumineuse sculptée par une LUMIÈRE DIRECTIONNELLE INTENSE. Jeux d'ombres cinématographiques créant un contraste fort entre obscurité et lumière. Poses statuesques et artistiques inspirées des campagnes haute joaillerie et couture contemporaines. Styling minimaliste NOIR ou monochrome, ÉPAULES DÉNUDÉES, tissus structurés ou satinés très sobres. Fond NOIR PROFOND ou gris anthracite. Atmosphère mystérieuse, puissante et intemporelle. Esthétique inspirée de campagnes Cartier, Dior Haute Joaillerie, Vogue et photographie mode luxe contemporaine. Rendu ultra réaliste, peau satinée, lumière sculpturale, profondeur de champ douce, élégance silencieuse et artistique, sans surcharge visuelle ni glamour excessif.`,
    ambiance: `Studio sombre minimaliste — fond noir profond ou dégradé gris anthracite, sans accessoires, sans décor, sans texture, ultra épuré. Lumière directionnelle intense unique (une seule source sur le côté ou en hauteur), sculpturale, créant des ombres cinématographiques marquées. Fort contraste entre les zones d'ombre profonde et le sujet brillamment éclairé. Ombres dramatiques, sculpturales, cinématographiques — éclairage clair-obscur comme les campagnes de haute joaillerie. Noirs profonds, hautes lumières vives, très peu de tons moyens. Palette : noir profond, gris anthracite, charbon foncé, avec un éclat sculptural unique sur la peau ou l'objet en ton chaud ou neutre. Aucun élément coloré. Ambiance : mystérieuse, puissante, intemporelle, sophistiquée, élégance silencieuse — jamais glamour excessif ni kitsch. Inspiration : campagne Cartier haute joaillerie, éditorial Dior Haute Joaillerie, portrait mode Vogue, magazine joaillerie luxe contemporain. Composition ultra épurée avec un espace négatif massif en noir profond. Le sujet occupe une zone précise, le reste est ombre.`,
  },
};

// === ACTIONS DE RETOUCHE (hors thèmes) ===
// Prompts d'action de retouche photo, traduits en français à partir
// des versions anglaises actuelles dans app/api/retouche-photo/route.ts.

type ActionPrompt = {
  label: string;
  description: string;  // À quoi sert cette action
  prompt: string;       // Le prompt FR
};

const ACTIONS_FR: Record<string, ActionPrompt> = {
  "fond-blanc": {
    label: "Fond blanc (packshot catalogue)",
    description: "Repositionne la bague sur fond 100% blanc pur, style catalogue Mood — préservation pixel-précise du design.",
    prompt: `Prends cette même bague Mood Collection et place-la sur un fond blanc catalogue pur, dans la pose signature catalogue Mood. La préservation pixel-précise du design est la priorité absolue. Garde EXACTEMENT la même forme et silhouette, les mêmes couleurs et matériaux (acier, titane, aluminium, or, etc.), la même décoration (compte chaque élément : si la bague a 4 rangs de pavé diamants, sort 4 rangs ; si elle a 26 pierres, sort 26 pierres). Ne simplifie pas, ne redessigne pas, ne réinterprète pas. Caméra au niveau de l'œil avec léger plongé (~10-15°), bague posée à plat horizontalement, légèrement inclinée en perspective 3/4 pour voir la bande extérieure décorée sur le dessus et le trou intérieur poli en ovale horizontal. Format carré 1:1, la bague remplit 85-95% du cadre, centrée. Fond blanc pur (#FFFFFF) — pas gris, pas crème. Découpe pixel-précise, aucun halo. Pas d'ombre portée sur la surface invisible (l'auto-ombre 3D de la bague reste). Nettoyage complet : pas de poussière, peluche, empreintes, rayures. Les rails de base (les deux bandes métalliques polies de chaque côté de l'addon) doivent être miroir-nickel impeccable. Pour la couleur intérieure : si la base extérieure est colorée (titane anodisé bleu, rose, violet, or, noir), l'intérieur visible à travers le trou est de la MÊME couleur (le titane anodisé est coloré partout). Si la base est en acier 316L neutre, l'intérieur est argent poli. Structure addon-base : l'addon (bande centrale décorée) remplit toute la rainure centrale entre les deux rails polis, sans débordement, sans espaces, à la même hauteur de surface. Lumière studio douce uniforme. Interdictions : pas de fond gris/crème, pas d'ombre portée, pas de redesign.`,
  },
  "fond-anthracite": {
    label: "Fond anthracite",
    description: "Repositionne la bague sur un fond anthracite uniforme (couleur photo signature Mood Collection).",
    prompt: `Place ce sujet sur un fond gris anthracite uniforme et propre (couleur hex #292928, le même fond sombre utilisé en photo produit Mood Collection). Garde le sujet exactement comme il est — mêmes couleurs, mêmes lumières, mêmes ombres, même position et même composition. Seul le fond est remplacé par la couleur anthracite uniforme. Style packshot professionnel, centré, ambiance lumière studio.`,
  },
  "amelioration": {
    label: "Amélioration (nettoyage + redressement)",
    description: "Nettoie les imperfections et redresse la bague — version pristine prête pour e-commerce premium.",
    prompt: `Retouche professionnelle packshot de cette photo de bague Mood Collection. Génère une version NETTOYÉE et REDRESSÉE avec les corrections suivantes : 1. Nettoie toutes les imperfections sur la surface de la bague : particules de poussière, empreintes digitales, fines rayures, traces, peluches, marques, micro-taches. La bague doit avoir l'air parfaitement neuve, comme sortant juste de la phase de polissage. 2. Redresse la bague : si elle est inclinée ou de travers, fais-la tourner doucement pour qu'elle soit parfaitement alignée avec l'horizontal/vertical naturel de la photo. Centre-la dans le cadre avec des marges confortables. 3. Améliore le métal/matériau : préserve et mets en valeur la texture naturelle (brossé, poli, anodisé, etc.), garde les couleurs fidèles, booste le contraste subtilement pour des bords nets, accentue les hautes lumières réfléchissantes sans en faire trop. 4. Garde IDENTIQUE : le fond, la direction de la lumière, le style de composition global, l'identité de la bague (même forme, couleur, matériau, finition, pierres). Le résultat doit ressembler à une bague tout juste retouchée par un photographe joaillerie professionnel pour une fiche e-commerce haut de gamme.`,
  },
  "lumiere-contraste": {
    label: "Lumière & contraste",
    description: "Améliore lumière + contraste pour un rendu qualité magazine luxe joaillerie.",
    prompt: `Amélioration professionnelle haute qualité de cette photo de bague Mood Collection pour une qualité magazine joaillerie luxe. Applique les corrections suivantes sur toute l'image : 1. LUMIÈRE : améliore significativement la dynamique d'exposition, récupère les détails des ombres, contrôle les hautes lumières, ajoute un effet subtil d'éclairage studio directionnel. La bague doit avoir des hautes lumières nettes et bien définies, et des ombres profondes et riches pour un effet 3D. 2. CONTRASTE : augmente clairement le contraste — noirs profonds, blancs lumineux, plage tonale complète. Évite l'aspect plat délavé. 3. NETTOIE LES PARASITES PARTOUT — sur la bague ET dans le décor/fond environnant : poussière, empreintes, fines rayures, peluches, fibres, cheveux, marques, taches. La surface, le tissu, le support, le fond doivent être impeccables. 4. CORRIGE LES IMPERFECTIONS DU DÉCOR : corrige les plis du tissu, la saleté sur les surfaces, l'incohérence de couleur, la poussière sur les feuilles de plantes, les marques d'eau, les taches sur le verre. 5. AUGMENTE LA NETTETÉ et la clarté sélectivement sur les bords de la bague et les pierres pour cet aspect magazine haut de gamme. 6. GARDE IDENTIQUE : composition, identité de la bague, style du décor, intention de palette. Résultat : un look photographie joaillerie luxe haut de gamme, prêt pour un magazine glacé ou une photo hero e-commerce.`,
  },
  "bague-portee": {
    label: "Bague portée (close-up éditorial luxe)",
    description: "Le prompt principal pour transformer une photo de bague en photo portée style magazine joaillerie luxe.",
    prompt: `Transforme cette photo de bague Mood Collection en une photographie éditoriale close-up haut de gamme de la bague portée sur une main, dans le style d'une campagne magazine joaillerie luxe (esthétique Cartier / Tiffany / Bvlgari). 1. LA BAGUE : garde-la absolument identique à la source — même forme, mêmes couleurs, même matériau, même finition, mêmes pierres, mêmes gravures, mêmes proportions. La bague est le héros de la photo, parfaitement nette, bien éclairée. 2. LA MAIN (par défaut si rien de spécifié) : main féminine élégante, ongles bien manucurés (French subtile propre ou couleur naturelle), peau bronzée/olive, pas d'autre bijou sur les autres doigts qui distrait. Pose naturelle douce : la main peut reposer contre le bras opposé, près de la clavicule/mâchoire, près du visage en le voilant partiellement, ou naturellement sur une surface douce. 3. TENUE en arrière-plan flou : un simple t-shirt blanc, OU un pull cachemire crème/beige, OU un blazer noir délicat — jamais l'attention principale, toujours en soutien. 4. CADRAGE : close-up serré sur la bague + main, la bague occupe 30-50% du cadre, focus parfait sur la bague (nette), profondeur de champ courte (arrière-plan flou), lumière studio chaude directionnelle qui flatte la peau. 5. LUMIÈRE : douce, chaude, légèrement directionnelle — comme un shot beauté. Capte joliment les reflets de la bague. La peau a l'air saine et lumineuse. 6. ARRIÈRE-PLAN : neutre, soft-focus, soutient la bague (peau/tissu/mur flou). Pas d'éléments distrayants, pas de désordre, pas de logo, pas de texte. 7. STYLE : éditorial haut de gamme, qualité magazine, sophistiqué, intime, contemporain. Comme un post Instagram d'une maison de joaillerie luxe.`,
  },
  "coffret": {
    label: "Coffret Mood",
    description: "Repositionne la bague dans le coffret Mood Collection (skai blanc capitonné), pose signature Mood.",
    prompt: `PRÉSENTATION COFFRET MOOD — Re-photographie cette même bague placée à l'intérieur d'un coffret de présentation Mood Collection, dans le style photo signature coffret Mood. La préservation pixel-précise du design est obligatoire : même forme exacte, mêmes couleurs, mêmes matériaux, même finition, mêmes pierres, mêmes gravures, même motif. Compte et préserve chaque élément décoratif (rangs de pavé, pierres, bandes addon, motifs). Si la base est en titane coloré anodisé (bleu, rose, violet, or, noir), l'intérieur est de la MÊME couleur. Si la base est en acier 316L, l'intérieur est argent acier poli. Caméra au niveau de l'œil avec léger plongé (~5-15°). ORIENTATION VERROUILLÉE (toujours identique pour chaque photo coffret) : la bague est DEBOUT SUR SA TRANCHE INFÉRIEURE sur le coussin de skai blanc (comme un pneu qui se tient au sol — pas couchée à plat, pas inclinée sur le côté). L'axe circulaire est HORIZONTAL : l'ouverture (le trou) est face au CÔTÉ DROIT du cadre. La bande extérieure DÉCORÉE/COLORÉE est entièrement visible à GAUCHE-FRONT, face à la caméra. L'INTÉRIEUR ARGENT POLI (trou) est visible à DROITE comme une ouverture en ovale doux captant la lumière. Angle 3/4 subtil. La bague est en focus net devant-centre. Format carré 1:1. La bague est GROSSE, remplit le cadre : 85-95% de la largeur, touche presque les bords gauche et droit (marge 2-5%). Seul un fin liseré de coussin visible en haut et en bas. La bague DOMINE la composition. Fond : intérieur du coffret Mood ouvert en skai blanc capitonné (texture matelassée douce visible mais floue). Lumière naturelle douce diffuse de la fenêtre, source unique en haut-gauche à ~45°. Reflet doux sur le bord supérieur, ombre légère en gradient sur le bas-droite. Ambiance : calme, intime, comme un coffret bijou ouvert dans la lumière du jour. Nettoyage impeccable : pas de poussière, empreintes, rayures, peluches. Rails miroir-nickel. Pierres scintillantes et brillantes. Structure addon-base : addon flush avec les rails, sans débordement, sans gaps. Interdictions : pas de fond blanc seamless studio, pas de mains/personnes, pas de logo/texte.`,
  },
  "redimensionner-bague": {
    label: "Redimensionner bague (changer largeur)",
    description: "Convertit une bague Mood d'une largeur (mm) à une autre, en préservant le design — motifs ronds restent ronds.",
    prompt: `REDIMENSIONNER LA(LES) BAGUE(S) — convertis la(les) bague(s) Mood Collection attachée(s) à une largeur de bande plus FINE (ou plus LARGE) SANS modifier le design. Si la photo source montre PLUSIEURS bagues (empilées, alignées, en pile, groupées) : compte-les soigneusement, la SORTIE doit montrer EXACTEMENT le même nombre de bagues (ex : 13 bagues en entrée → 13 bagues en sortie, jamais plus, jamais moins). Convertis CHAQUE bague individuellement à la largeur cible. Préserve l'arrangement, l'ordre, la position, l'espacement exact. Préserve l'identité couleur/finition/décoration de chaque bague. PRÉSERVATION DU DESIGN (NON NÉGOCIABLE) : même identité de bague exacte (matériau, couleur, finition, pierres, motif). Les MOTIFS DÉCORATIFS (bulles, cercles, points, pierres, ornements) gardent leur forme EXACTE — les bulles rondes restent parfaitement RONDES, jamais étirées en ovale, jamais écrasées. Chaque motif garde son rapport d'aspect d'origine (une bulle ronde de 2mm reste une bulle ronde de 2mm, pas un ovale 2x1.3mm). CHANGEMENT DE LARGEUR DE BANDE : la largeur source et la largeur cible sont spécifiées dans la note utilisateur. Réduis (ou augmente) UNIQUEMENT la largeur verticale de la bande (l'épaisseur vue de côté). Garde le diamètre global INCHANGÉ (même taille de doigt). Adapte la disposition/le nombre des motifs naturellement : si tu réduis la largeur, les motifs peuvent être plus petits proportionnellement OU moins de motifs tiennent sur la bande plus fine — mais chaque motif GARDE sa forme ronde. Si tu augmentes, ajoute proportionnellement plus d'espace autour des motifs OU des motifs plus grands (toujours même forme, juste à l'échelle). STYLE PHOTO PRÉSERVÉ : même angle caméra, même éclairage, même fond, même direction d'ombre, même étalonnage couleur. La sortie ressemble à la MÊME photo d'une version PLUS FINE de la même bague. Interdictions : pas d'ovalisation des motifs ronds, pas de simplification du design, pas de changement matériau/couleur/finition/pierres, pas de changement d'angle caméra ou de style d'éclairage, pas de texte/logo/filigrane.`,
  },
  "produit-multiple": {
    label: "Produit multiple (2-6 bagues)",
    description: "Compose plusieurs bagues Mood ensemble dans une seule scène éditoriale dispersée style magazine.",
    prompt: `COMPOSITION ÉDITORIALE MULTI-BAGUES — Crée une seule image montrant TOUTES les bagues Mood Collection attachées composées ensemble dans UNE scène éditoriale. PRÉSERVATION D'IDENTITÉ PIXEL (NON NÉGOCIABLE) : chaque bague montrée dans les images de référence attachées doit être reproduite PIXEL-IDENTIQUE en sortie — même forme exacte, même taille, mêmes couleurs, même matériau, même finition, mêmes pierres, même motif, même addon, même décoration. NE PAS redessigner, simplifier, fusionner ou dupliquer les bagues. Compte les images de référence : si 4 références sont attachées, montre EXACTEMENT 4 bagues différentes en sortie (une par référence). N'invente jamais de bagues supplémentaires. DISPOSITION — ÉDITORIAL DISPERSÉ (campagne magazine, PAS grille) : disperse les bagues NATURELLEMENT à travers la scène — PAS alignées en grille, PAS en rang parfait, PAS empilées. Chaque bague positionnée à une hauteur/angle/profondeur différente — certaines debout, certaines couchées à plat, certaines penchées, sur des plans légèrement différents. La composition ressemble à une campagne magazine joaillerie luxe : artistique, équilibrée, avec de l'espace négatif aéré entre les bagues. Hiérarchie : une bague peut être légèrement plus prominente au premier plan (point focal), les autres en soutien autour. Les bagues NE SE TOUCHENT PAS et ne se chevauchent pas — espace de respiration. Composition totale harmonieuse. SCÈNE COHÉRENTE : TOUTES les bagues partagent la MÊME LUMIÈRE, la MÊME SURFACE/ENVIRONNEMENT, la MÊME ATMOSPHÈRE. Par défaut : lumière studio douce directionnelle, fond blanc seamless neutre avec ombre subtile (override par le thème actif si applicable). Toutes les bagues parfaitement nettes, miroir-impeccables, pierres brillantes, sans poussière. Sortie : une seule image de composition éditoriale, qualité impression magazine.`,
  },
};

export async function GET() {
  const themes = Object.entries(PROMPTS_FR_AMILA).map(([key, p]) => ({
    key,
    label: p.label,
    porte: p.porte,
    ambiance: p.ambiance,
    porte_homme: p.porte_homme || null,
  }));
  const actions = Object.entries(ACTIONS_FR).map(([key, a]) => ({
    key,
    label: a.label,
    description: a.description,
    prompt: a.prompt,
  }));
  return NextResponse.json({ themes, actions });
}
